status = [
    "clippy",
    "doc",
    "doclinks",
    "format",
    "precompiled",
    "template",
    "test",
    "xplat (macos-latest)",
    "xplat (ubuntu-latest)",
    "xplat (windows-latest)"
]
delete_merged_branches = true
